version: '2'
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app/
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings_docker
    depends_on:
      - postgres
    command: bash -c "sleep 3 && python ./manage.py migrate
      && python ./manage.py runserver 0.0.0.0:8000"

  postgres:
    image: "postgres:10"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
     pgdata:
