version: '2'
services:
  app:
    build: ./app
    volumes:
      - ./app/:/app/
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings_docker
    volumes:
      - media:/app/media
      - static:/app/static
    depends_on:
      - db
    command: bash -c "sleep 3
      && python ./manage.py migrate
      && gunicorn wsgi:application --workers 2 --bind :8000"
    env_file:
      - docker.env

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "127.0.0.1:8000:80"
    volumes_from:
      - app
    links:
      - app:app
    depends_on:
      - app

volumes:
     pgdata:
     media:
     static:
