version: '3.3'
services:
  app:
    build: ./app
    depends_on:
      - db
      - memcached
    command: bash -c "sleep 3
      && python ./manage.py migrate
      && gunicorn wsgi:application --workers 2 --bind :8000"

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - media:/app/media
      - static:/app/static
    links:
      - app:app
    depends_on:
      - app

  memcached:
    image: memcached:alpine

volumes:
     pgdata:
     media:
     static:
